### PR TITLE
Update to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by ViktorHofer**
- Uses the new project-sdk format.
- Upgrade to .NET Standard 2.0 for a minimal dependency graph

### CODE REVIEW

**Comment by ViktorHofer** [comment]
any update?

**Comment by ViktorHofer** [comment]
Project seems dead. Closing.

**Comment by JohnyWS** [comment]
Dang - have you found alternatives @ViktorHofer ?

**Comment by ViktorHofer** [comment]
Use MarkdownLog.NS20 if you just want to have a netstandard version of it. That's my self published version of this PR

**Comment by Wheelies** [comment]
Sorry — I’ve been a bit rubbish, Viktor. The project is still alive but I’ve just taken my eye off the ball. I am determined to re-invigorate it and I have some time tomorrow in which I can review your pull request. 

Upgrading the project to .NET standard is a great idea!

Thanks for your patience,
Stu

**Comment by ViktorHofer** [comment]
Sounds great, will reopen.

**Pull request merged**
